FL_COUNTIES = [
    {
        "slug": "alachua",
        "display_name": "Alachua",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "alachua_spider",
        "url_template": "https://www.alachuaclerk.com/propertysearch/search.aspx?owner={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "baker",
        "display_name": "Baker",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "baker_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "bay",
        "display_name": "Bay",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "bay_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "bradford",
        "display_name": "Bradford",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "bradford_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "brevard",
        "display_name": "Brevard",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "brevard_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "broward",
        "display_name": "Broward",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": True,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": False,
        },
        "spider_key": "broward_spider",
        "url_template": "https://www.broward.org/propertysearch/Pages/OwnerSearch.aspx?owner={query}",
        "query_param_style": "template",
        "pagination": "next_link",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "calhoun",
        "display_name": "Calhoun",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "calhoun_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "charlotte",
        "display_name": "Charlotte",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "charlotte_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "citrus",
        "display_name": "Citrus",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "citrus_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "clay",
        "display_name": "Clay",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "clay_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "collier",
        "display_name": "Collier",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "collier_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "columbia",
        "display_name": "Columbia",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "columbia_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "desoto",
        "display_name": "DeSoto",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "desoto_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "dixie",
        "display_name": "Dixie",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "dixie_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "duval",
        "display_name": "Duval",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "duval_spider",
        "url_template": "https://www.duvalclerk.com/property-search?owner={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "escambia",
        "display_name": "Escambia",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "escambia_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "flagler",
        "display_name": "Flagler",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "flagler_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "franklin",
        "display_name": "Franklin",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "franklin_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "gadsden",
        "display_name": "Gadsden",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "gadsden_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "gilchrist",
        "display_name": "Gilchrist",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "gilchrist_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "glades",
        "display_name": "Glades",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "glades_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "gulf",
        "display_name": "Gulf",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "gulf_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "hamilton",
        "display_name": "Hamilton",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "hamilton_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "hardee",
        "display_name": "Hardee",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "hardee_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "hendry",
        "display_name": "Hendry",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "hendry_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "hernando",
        "display_name": "Hernando",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "hernando_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "highlands",
        "display_name": "Highlands",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "highlands_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "hillsborough",
        "display_name": "Hillsborough",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "hillsborough_spider",
        "url_template": "https://www.hillsboroughcounty.org/property-search?owner={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "holmes",
        "display_name": "Holmes",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "holmes_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "indian_river",
        "display_name": "Indian River",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "indian_river_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "jackson",
        "display_name": "Jackson",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "jackson_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "jefferson",
        "display_name": "Jefferson",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "jefferson_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "lafayette",
        "display_name": "Lafayette",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "lafayette_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "lake",
        "display_name": "Lake",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "lake_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "lee",
        "display_name": "Lee",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "lee_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "leon",
        "display_name": "Leon",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "leon_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "levy",
        "display_name": "Levy",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "levy_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "liberty",
        "display_name": "Liberty",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "liberty_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "madison",
        "display_name": "Madison",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "madison_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "manatee",
        "display_name": "Manatee",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "manatee_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "marion",
        "display_name": "Marion",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "marion_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "martin",
        "display_name": "Martin",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "martin_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "miami_dade",
        "display_name": "Miami-Dade",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "miami_dade_spider",
        "url_template": "https://www.miami-dadeclerk.com/ocs/Search.aspx?search={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "monroe",
        "display_name": "Monroe",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "monroe_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "nassau",
        "display_name": "Nassau",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "nassau_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "okaloosa",
        "display_name": "Okaloosa",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "okaloosa_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "okeechobee",
        "display_name": "Okeechobee",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "okeechobee_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "orange",
        "display_name": "Orange",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": True,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "orange_spider",
        "url_template": "https://www.orangecountyfl.net/property-search?owner={query}",
        "query_param_style": "template",
        "pagination": "page_param",
        "page_param": "page",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "osceola",
        "display_name": "Osceola",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "osceola_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "palm_beach",
        "display_name": "Palm Beach",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "palm_beach_spider",
        "url_template": "https://www.pbcgov.org/papa/searchproperty.aspx?owner={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "pasco",
        "display_name": "Pasco",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "pasco_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "pinellas",
        "display_name": "Pinellas",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "pinellas_spider",
        "url_template": "https://www.pinellascounty.org/property-search?owner={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "polk",
        "display_name": "Polk",
        "status": "live",
        "capabilities": {
            "supports_query_param": True,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "polk_spider",
        "url_template": "https://www.polkcountyclerk.net/property-search?owner={query}",
        "query_param_style": "template",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "putnam",
        "display_name": "Putnam",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "putnam_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "santa_rosa",
        "display_name": "Santa Rosa",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "santa_rosa_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "sarasota",
        "display_name": "Sarasota",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "sarasota_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "seminole",
        "display_name": "Seminole",
        "status": "live",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": True,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "seminole_spider",
        "url_template": "",
        "query_param_style": "form",
        "form_url": "https://www.seminolecountyfl.gov/property-search",
        "form_fields_template": {"owner": "{query}"},
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "st_johns",
        "display_name": "St. Johns",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "st_johns_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "st_lucie",
        "display_name": "St. Lucie",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "st_lucie_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "sumter",
        "display_name": "Sumter",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "sumter_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "suwannee",
        "display_name": "Suwannee",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "suwannee_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "taylor",
        "display_name": "Taylor",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "taylor_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "union",
        "display_name": "Union",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "union_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "volusia",
        "display_name": "Volusia",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "volusia_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "wakulla",
        "display_name": "Wakulla",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "wakulla_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "walton",
        "display_name": "Walton",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "walton_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
    {
        "slug": "washington",
        "display_name": "Washington",
        "status": "stub",
        "capabilities": {
            "supports_query_param": False,
            "needs_form_post": False,
            "needs_pagination": False,
            "needs_js": False,
            "supports_owner_search": True,
            "supports_address_search": True,
        },
        "spider_key": "washington_spider",
        "url_template": "",
        "query_param_style": "none",
        "pagination": "none",
        "page_param": "",
        "parcel_layer": {
            "type": "none",
            "endpoint": "",
            "id_field": "",
            "supports_geometry": False,
        },
    },
]
